name: upcom-launcher
version: 0.1.0
authors:
- Mike Lewis <mike@updroid.com>
description: A launcher tab for UpDroid Commander
homepage: https://www.updroid.com
environment:
  sdk: '>=1.9.3 <2.0.0'
dependencies:
  upcom-api:
    path: ../upcom-api/
  quiver: any
